language: node_js
node_js:
-11.6.0
cache: npm

install:
  -npm ci

script:
  -npm test
  -npm run build

  deploy:
    provider: pages
    skip-cleanup: true
    gitub-token: $GITHUB_TOKEN
    on:
      branch: gh-pages