language: node_js
node_js:
-12.13.0
cache:
  directories:
    - "node_modules"

install:
  -npm ci

script:
  -npm test
  -npm run build

  deploy:
    provider: pages
    skip-cleanup: true
    gitub-token: $GITHUB_TOKEN
    on:
    push
      branch: master
